joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 1
   
# Joint Group Position Controller
joint_group_position_controller:
   type: robot_controllers/JointGroupPosition
   root_name: joint1
   tip_name: joint4


# Cartesian Velocity Controller
cartesian_velocity_controller:
   type: robot_controllers/CartesianVelocityControl
   root_name: link_1
   tip_name: link_grinder


joint_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    joint1:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02                     # Not enforced if unspecified
    joint2:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02  
    joint3:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02  
    joint4:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02  

#robot_gripper_controller:
#  type: "position_controllers/JointTrajectoryController"
#  joints:
#    - joint5
